components:
  layer:
    type: layer
    path: deployment/terraform/lambda-layer
    source_path: deployment/terraform/lambda-layer/shared-layer

  image-processor:
    type: lambda
    path: deployment/terraform/image-processor
    source_path: deployment/terraform/image-processor/src

  ses:
    type: lambda
    path: deployment/terraform/travel-contact
    source_path: deployment/terraform/travel-contact/lambda/src