components:
  layer:
    type: layer
    path: deployment/terraform/lambda-layer
    source_path: deployment/terraform/lambda-layer/shared-layer
    tf_var_name: "filename"

  image-processor:
    type: lambda
    path: deployment/terraform/image-processor
    source_path: deployment/terraform/image-processor/src
    tf_var_name: "lambda_zip_path"

  ses:
    type: lambda
    path: deployment/terraform/travel-contact
    source_path: deployment/terraform/travel-contact/lambda/src
    tf_var_name: "lambda_zip_path"