package services

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"
	"time"

	"api/internal/models"
)

// LocalImageService handles fetching images from local filesystem
// For local development only - no processing, just serves files
type LocalImageService struct {
	*BaseImageService
}

func NewLocalImageService(config models.ImageServiceConfig) *LocalImageService {
	if config.LocalImageDir != "" {
		os.MkdirAll(config.LocalImageDir, 0755)
	}

	return &LocalImageService{
		BaseImageService: NewBaseImageService(config),
	}
}

// GetImages retrieves images from local filesystem
func (s *LocalImageService) GetImages(ctx context.Context) ([]models.ImageInfo, error) {
	if s.Config.EnableCache && len(s.Cache.Images) > 0 && !s.Cache.IsExpired() {
		log.Printf("Returning %d images from local cache", len(s.Cache.Images))
		return s.Cache.Images, nil
	}

	log.Printf("Fetching images from local directory: %s", s.Config.LocalImageDir)

	files, err := os.ReadDir(s.Config.LocalImageDir)
	if err != nil {
		return nil, fmt.Errorf("failed to read image directory: %v", err)
	}

	var images []models.ImageInfo

	for _, file := range files {
		if file.IsDir() {
			continue
		}

		name := file.Name()
		ext := strings.ToLower(filepath.Ext(name))

		if !isLocalImageExt(ext) {
			continue
		}

		// Skip processed files - they're generated by Lambda in production
		if strings.Contains(name, "thumb_") || strings.Contains(name, "medium_") ||
			strings.Contains(name, "carousel_") {
			continue
		}

		info := s.getLocalImageInfo(name)
		if info != nil {
			images = append(images, *info)
		}
	}

	if s.Config.EnableCache {
		s.Cache.Images = images
		s.Cache.UpdatedAt = time.Now()
	}

	log.Printf("Retrieved %d images from local directory", len(images))
	return images, nil
}

func (s *LocalImageService) getLocalImageInfo(filename string) *models.ImageInfo {
	baseName := strings.TrimSuffix(filename, filepath.Ext(filename))

	// For local development, just use the original files
	fullPath := filepath.Join(s.Config.LocalImageDir, filename)

	// Check for processed versions (if they exist locally)
	thumbPath := filepath.Join(s.Config.LocalImageDir, fmt.Sprintf("thumb_%s.jpg", baseName))
	mediumPath := filepath.Join(s.Config.LocalImageDir, fmt.Sprintf("medium_%s.jpg", baseName))

	thumbURL := "/" + thumbPath
	mediumURL := "/" + mediumPath

	// If processed versions don't exist, use original
	if _, err := os.Stat(thumbPath); os.IsNotExist(err) {
		thumbURL = "/" + fullPath
	}
	if _, err := os.Stat(mediumPath); os.IsNotExist(err) {
		mediumURL = "/" + fullPath
	}

	return &models.ImageInfo{
		Full:   "/" + fullPath,
		Thumb:  thumbURL,
		Medium: mediumURL,
		Alt:    strings.ReplaceAll(baseName, "-", " "),
		Width:  1200,
		Height: 800,
	}
}

func isLocalImageExt(ext string) bool {
	validExts := []string{".jpg", ".jpeg", ".png", ".webp", ".gif"}
	for _, validExt := range validExts {
		if ext == validExt {
			return true
		}
	}
	return false
}
