variables:
  RUN_GO_TESTS:
    value: "true"
    options:
      - "true"
      - "false"
    description: "Select whether to run Golang application tests"

stages:
  - test

test:golang-api:
  stage: test
  image: golang:1.25-alpine
  rules:
    # 1. ONLY run when manually triggered via GitLab UI ("Run pipeline") with RUN_GO_TESTS="true"
    - if: '$CI_PIPELINE_SOURCE == "web" && $RUN_GO_TESTS == "true"'
      when: always

    # 2. Never run on standard pushes, merge requests, or commits
    - when: never

  before_script:
    - apk add --no-libc-dev gcc musl-dev # Required if CGO or race detector is enabled
    - cd api                          

  script:
    - go mod download
    - go test -v -race -cover ./...
