package:
  stage: package
  image: python:3.13-slim
  rules:
    - if: '$DEPLOY_TARGET =~ /^(cloudfront|ses)$/'
      when: never
    - when: always
  before_script:
    - apt-get update && apt-get install -y zip bash > /dev/null
    - pip install pyyaml > /dev/null
  script:
    - mkdir -p ${ARTIFACTS_DIR}
    - python ${SCRIPTS_DIR}/package.py --config ${COMPONENTS_CONFIG} --artifacts ${ARTIFACTS_DIR} --component ${DEPLOY_TARGET}
  artifacts:
    paths:
      - ${ARTIFACTS_DIR}/